export const en = {
  name: "Metadata Fixer",
  lint: "Fix metadata",
  publicationStyle: "Conference names",
  retrievedNames: "Original",
  standardNames: "Standard",
  shortNames: "Short",
  settingsHelp: "Fill missing fields and fix errors.",
  apiBlocked: "Access blocked",
  apiInvalid: "Non-JSON response",
  ambiguous: "No reliable match",
  noDOI: "No DOI found (optional)",
  conferences: "Conference rules",
  conferenceHelp: "CCF 2026 · 386 conferences · 10 categories",
  formatPublication: "Use CCF names",
  formatHelp: "Format Proceedings Title; omit edition and year.",
  configureConference: "Configure",
  backup: "Backup",
  aliases: "Aliases (one per line)",
  conferenceName: "Conference name",
  itemType: "Item type",
  typeConference: "Conference Paper",
  typeBookSection: "Book Section",
  typeJournal: "Journal Article",
  removeEditors: "Remove editors",
  enabled: "Enabled",
  commonTitle: "Standard name",
  unmapped: "No maintained CCF mapping",
  searchConferences: "Search name, acronym or alias",
  all: "All",
  category: "Category",
  page: "Page",
  previous: "Previous",
  next: "Next",
  noConferenceMatches: "No matching conference rules",
  preserveJournals: "Keep journal articles",
  excludeAliases: "Exclude aliases (one per line)",
  overridePublication: "Custom name (optional)",
  useMaintainedName: "Use the publisher-maintained name",
  openCatalog: "CCF official catalog",
  resetConference: "Reset this conference",
  configurationJSON: "Configuration JSON",
  exportRules: "Export configuration",
  importRules: "Import configuration",
  invalidConfiguration: "Invalid configuration",
  addConference: "Add conference",
  removeRule: "Remove rule",
  resetRules: "Reset to bundled rules",
  saveRules: "Save configuration",
  cancel: "Cancel",
  status: "Status",
  title: "Title",
  working: "Updating…",
  complete: "Complete",
  cancelled: "Cancelled",
  updated: "Updated",
  skipped: "Skipped",
  noChanges: "No changes",
  failed: "Failed",
  noPublished: "No published version found",
  partial: "No match; some sources failed",
  warning: "Details",
  close: "Close",
  unsupported:
    "Retrieved record is not a verified published article or conference paper",
  empty: "No editable items selected",
  cancelledHelp: "Updates stopped.",
};
export type Strings = typeof en;
export const zh: Strings = {
  name: "Metadata Fixer",
  lint: "修正元数据",
  publicationStyle: "会议名称",
  retrievedNames: "原名",
  standardNames: "标准全名",
  shortNames: "简洁缩写",
  settingsHelp: "补全空字段，修正错误。",
  apiBlocked: "访问受限",
  apiInvalid: "接口返回非 JSON 内容",
  ambiguous: "无法可靠匹配",
  noDOI: "未找到 DOI（可为空）",
  conferences: "会议规则",
  conferenceHelp: "CCF 2026 · 386 个会议 · 10 个领域",
  formatPublication: "使用 CCF 名称",
  formatHelp: "规范化 Proceedings Title，不含届数和年份。",
  configureConference: "配置",
  backup: "备份",
  aliases: "别名（每行一个）",
  conferenceName: "会议名称",
  itemType: "条目类型",
  typeConference: "会议论文",
  typeBookSection: "图书章节",
  typeJournal: "期刊文章",
  removeEditors: "移除 editor",
  enabled: "启用",
  commonTitle: "标准全名",
  unmapped: "尚无维护的 CCF 名称映射",
  searchConferences: "搜索名称、缩写或别名",
  all: "全部",
  category: "领域",
  page: "页",
  previous: "上一页",
  next: "下一页",
  noConferenceMatches: "没有匹配的会议规则",
  preserveJournals: "保留期刊文章",
  excludeAliases: "排除名称（每行一个）",
  overridePublication: "自定义名称（可选）",
  useMaintainedName: "使用发布者维护的规范名称",
  openCatalog: "CCF 官方目录",
  resetConference: "恢复本会议默认配置",
  configurationJSON: "JSON 配置",
  exportRules: "导出配置",
  importRules: "导入配置",
  invalidConfiguration: "无效配置",
  addConference: "添加会议",
  removeRule: "删除规则",
  resetRules: "恢复内置规则",
  saveRules: "保存配置",
  cancel: "取消",
  status: "状态",
  title: "标题",
  working: "正在更新…",
  complete: "已完成",
  cancelled: "已取消",
  updated: "已更新",
  skipped: "已跳过",
  noChanges: "无变更",
  failed: "失败",
  noPublished: "未找到正式发表版本",
  partial: "未找到匹配；部分来源请求失败",
  warning: "详情",
  close: "关闭",
  unsupported: "检索结果不是可验证的正式发表文章或会议论文",
  empty: "未选中可编辑的文献条目",
  cancelledHelp: "已停止更新。",
};
