export const en = {
  name: "Metadata Fixer",
  lint: "Fix metadata",
  publicationStyle: "Proceedings titles",
  retrievedNames: "Original",
  standardNames: "Standard",
  shortNames: "Short",
  settingsHelp:
    "Find published versions, add missing DOIs and correct bibliographic metadata.",
  apiBlocked: "Access blocked",
  apiInvalid: "Non-JSON response",
  ambiguous: "No reliable match",
  noDOI: "No DOI found (optional)",
  formatHelp:
    "Choose how proceedings titles are written. Standard and Short omit the conference edition and year.",
  cancel: "Cancel",
  status: "Status",
  title: "Title",
  waiting: "Waiting",
  working: "Updating…",
  cancelled: "Cancelled",
  updated: "Updated",
  skipped: "Skipped",
  noChanges: "No changes",
  failed: "Failed",
  noPublished: "No published version found",
  partial: "No match; some sources failed",
  close: "Close",
  unsupported:
    "Retrieved record is not a verified published article or conference paper",
  empty: "No editable items selected",
};
export type Strings = typeof en;
export const zh: Strings = {
  name: "Metadata Fixer",
  lint: "修正元数据",
  publicationStyle: "论文集名称",
  retrievedNames: "原名",
  standardNames: "标准全名",
  shortNames: "缩写",
  settingsHelp: "查找正式发表版本，补全 DOI，并修正文献信息。",
  apiBlocked: "访问受限",
  apiInvalid: "接口返回非 JSON 内容",
  ambiguous: "无法可靠匹配",
  noDOI: "未找到 DOI（可为空）",
  formatHelp: "选择论文集名称的写法。标准全名和缩写不包含会议届数及年份。",
  cancel: "取消",
  status: "状态",
  title: "标题",
  waiting: "等待中",
  working: "正在更新…",
  cancelled: "已取消",
  updated: "已更新",
  skipped: "已跳过",
  noChanges: "无变更",
  failed: "失败",
  noPublished: "未找到正式发表版本",
  partial: "未找到匹配；部分来源请求失败",
  close: "关闭",
  unsupported: "检索结果不是可验证的正式发表文章或会议论文",
  empty: "未选中可编辑的文献条目",
};
